Added a getting-setup markdown doc for the website
bitcoin-s/bitcoin-s pull request #1167
Opened 2020-02-25 18:51 UTC by nkohen

2020-02-25 19:05 UTC, benthecarman commented on website/versioned_docs/version-0.2.0/getting-setup.md
> +You should be able to test your secp256k1 installation by running `sbt console` in your bitcoin-s directory and then running
needs to tbe `sbt core/console`

2020-02-25 19:05 UTC, benthecarman commented on website/versioned_docs/version-0.2.0/getting-setup.md
> +scala> Secp256k1Context.isEnabled()
Add a warning that this may cause an error message about logging but is not a concern

2020-02-25 19:05 UTC, benthecarman commented on website/versioned_docs/version-0.2.0/getting-setup.md
> +addresstype=p2sh-segwit
these shouldn't be needed

2020-02-25 19:42 UTC, benthecarman approved these changes
LGTM

2020-02-25 20:05 UTC, benthecarman requested changes

2020-02-25 20:05 UTC, benthecarman commented on website/versioned_docs/version-0.2.0/getting-setup.md
> +$HOME/.bitcoin-s/binaries/bitcoind/bitcoin-0.18.99/bin/bitcoin-cli --datadir=[path/to/conf/directory] --rpcport=18332 generatetoaddress 200 [address]
Don't need the `--rpcport=18332`

2020-02-25 20:05 UTC, benthecarman commented on website/versioned_docs/version-0.2.0/getting-setup.md
> +$HOME/.bitcoin-s/binaries/bitcoind/bitcoin-0.18.99/bin/bitcoind --datadir=[path/to/conf/directory] --rpcport=18332
Don't need the `--rpcport=18332`

2020-02-26 14:16 UTC, Christewart commented on website/versioned_docs/version-0.2.0/getting-setup.md
> +# Getting Setup With Bitcoin-S
This is not in the right place, you need to place this inside of `docs/` folder. You may want to replace the `getting-started.md` file there? 

For more infromation on how the website works see: 

https://bitcoin-s.org/docs/next/contributing-website

If you are not going to replace the existing file, you need to update `sidebars.json` to how this new file. 

See this PR: https://github.com/bitcoin-s/bitcoin-s/pull/948

2020-02-26 18:11 UTC, Christewart commented on docs/applications/dlc.md
> +
I think you need to add a step here for checking out our feature branch

2020-02-26 19:03 UTC, benthecarman approved these changes

2020-02-26 20:09 UTC, merged