Ignore immature coinbase outputs when funding a transaction
bitcoin-s/bitcoin-s pull request #1365
Opened 2020-04-23 16:43 UTC by benthecarman

Built on #1364 so I could change `FundTransactionHandlingTest` to `fundWalletWithBitcoind` without needing to rewrite the tests.

Fixes #1357

2020-04-23 18:37 UTC, nkohen approved these changes

2020-04-24 17:29 UTC, Christewart requested changes

2020-04-24 17:29 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/transaction/TransactionOutPoint.scala
> +  def !==(outPoint: TransactionOutPoint): Boolean =
why `!==` and not `!=`?

2020-04-24 17:29 UTC, Christewart commented on wallet/src/main/scala/org/bitcoins/wallet/internal/FundTransactionHandling.scala
> +            confsOpt.isDefined && confsOpt.get > 100
Let's `100` into `Consensus.coinbaseMaturity` or something like that

2020-04-24 17:44 UTC, Christewart approved these changes

2020-04-24 23:04 UTC, merged