Added BlockTimeStamp abstraction for BlockStamps that aren't hashes
bitcoin-s/bitcoin-s pull request #1573
Opened 2020-06-15 21:24 UTC by nkohen

(from DLC branch's `BlockStampWithFuture`)

2020-06-15 21:51 UTC, benthecarman approved these changes

2020-06-16 11:36 UTC, Christewart requested changes

2020-06-16 11:36 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/BlockStamp.scala
> +object BlockTimeStamp {
`extends StringFactory`

2020-06-16 11:36 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/BlockStamp.scala
> +  final val LOCKTIME_THRESHOLD: Int = 500000000
```scala
final val LOCKTIME_THRESHOLD: Int = TransactionConstants.locktimeThreshold.toInt
```

2020-06-16 11:36 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/BlockStamp.scala
>    object BlockTime {
`extends StringFactory`

2020-06-16 14:56 UTC, benthecarman approved these changes

2020-06-16 15:54 UTC, Christewart approved these changes

2020-06-16 15:54 UTC, merged