Fix All Loggers!
bitcoin-s/bitcoin-s pull request #1695
Opened 2020-07-24 21:52 UTC by nkohen

Fixes #1688 and more!

Fixed logging so that appenders are always started when a cached logger is retrieved, for some reason logger appenders get detached and I don't know why.

Previously what was happening is that loggers were cached per-object but appenders were stopped/detached the moment another object queried for a cached logger. The resulting behavior was that the first logs from an object/instance were seen and then once any other object did any logging the logs from the previous object would stop being added.

2020-07-24 22:04 UTC, benthecarman commented on db-commons/src/main/scala/org/bitcoins/db/AppLoggers.scala
> +    }
this should probably be a function in `AppLoggers`

2020-07-24 22:04 UTC, benthecarman commented on db-commons/src/main/scala/org/bitcoins/db/AppLoggers.scala
> +    }
ditto

2020-07-25 21:26 UTC, Christewart approved these changes
Seems to work for me on #1697

2020-07-25 21:46 UTC, Christewart requested changes
Actually I lied, on #1697 it seems that STDOUT is working, but nothing is being written to `$HOME/.bitcoin-s/testnet3/bitcoin-s.log` 

If you look at this image, the upper right pane is my STDOUT, and the bottom right is me ` tail -F ~/.bitcoin-s/testnet3/bitcoin-s.log`. You can see that nothing is going to the log file 
![Screenshot from 2020-07-25 16-43-44](https://user-images.githubusercontent.com/3514957/88466862-4cf8a000-ce96-11ea-986c-c372aa311982.png)

2020-07-28 12:10 UTC, Christewart approved these changes

2020-07-28 12:11 UTC, Christewart commented
Logging works on #1697 as of e9e3702. Nice job @nkohen !! :tada:

2020-07-28 12:13 UTC, merged