Optimize getBestFilter functions
bitcoin-s/bitcoin-s pull request #1715
Opened 2020-07-28 19:30 UTC by benthecarman

Attempt at #1700 

Reduces the number of database reads needed from 2 -> 1. I think this is the most optimal sql query we can use to get the filter with the most work. 

This is the resulting sql query 
``` 
select s13."hash", s13."filter_type", s13."bytes", s13."height", s13."block_hash" from "cfilters" s13, "block_headers" s14 where (s14."chain_work" = (select max(s21."chain_work") from "cfilters" s20, "block_headers" s21 where s20."block_hash" = s21."hash")) and (s13."block_hash" = s14."hash") limit 1
```

2020-07-28 20:17 UTC, nkohen approved these changes

2020-07-28 22:24 UTC, Christewart approved these changes

2020-07-29 18:11 UTC, rorp requested changes
It doesn't fix full table scans for `MAX(chain_work)` and `WHERE chain_work = ?`

2020-07-29 19:48 UTC, benthecarman commented
Added an index for the chain work, should be much faster now

2020-07-30 12:05 UTC, Christewart commented on chain/src/main/resources/sqlite/chain/migration/V4__chain_work_to_varchar.sql
> +CREATE TABLE "block_headers_temp" ("height" INTEGER NOT NULL,"hash" VARCHAR(254) PRIMARY KEY NOT NULL,"version" INTEGER NOT NULL,"previous_block_hash" VARCHAR(254) NOT NULL,"merkle_root_hash" VARCHAR
I think we need postgres too?

2020-07-30 15:23 UTC, rorp approved these changes
👍

2020-07-30 15:47 UTC, merged