Correcly use reference.conf file
bitcoin-s/bitcoin-s pull request #1869
Opened 2020-08-21 17:25 UTC by benthecarman

Previously, our reference.conf file wasn't being used because it was in `app/server/resources` and `AppConfig` looks for it in `db-commons/resources/`. This moves it to it's correct location.

This revealed a bug with the `filter-header-batch-size` config option where it would not be able to read the default value because having the network specific made it an OBJECT type thus overwriting it. This changes it to have a `default` option instead.

Fixed some typos as well.

2020-08-23 12:53 UTC, Christewart requested changes

2020-08-23 12:53 UTC, Christewart commented on db-commons/src/main/resources/reference.conf
> +            filter-header-batch-size.default = 2000
I think we need to update documentation on the website

https://bitcoin-s.org/docs/next/config/configuration#example-configuration-file

and probably `testkit/reference.conf` too

2020-08-24 01:05 UTC, benthecarman commented on db-commons/src/main/resources/reference.conf
> +            filter-header-batch-size.default = 2000
Fixed

2020-08-24 11:30 UTC, Christewart approved these changes

2020-08-24 11:30 UTC, merged