Added Schnorr signature point computation test vectors
bitcoin-s/bitcoin-s pull request #2095
Opened 2020-09-30 23:03 UTC by nkohen

and their corresponding generators and tests.

2020-09-30 23:19 UTC, benthecarman requested changes

2020-09-30 23:19 UTC, benthecarman commented on dlc/src/main/scala/org/bitcoins/dlc/testgen/SchnorrSigPointTestVector.scala
> +  def privNonce: ECPrivateKey = inputs.privKey
this should be `inputs.privNonce`

2020-09-30 23:19 UTC, benthecarman commented on dlc/src/main/scala/org/bitcoins/dlc/testgen/SchnorrSigPointTestVectorGen.scala
> +      )
nit: use a `Vector.fill` here

2020-10-01 00:55 UTC, nkohen commented on dlc/src/main/scala/org/bitcoins/dlc/testgen/SchnorrSigPointTestVector.scala
> +  def privNonce: ECPrivateKey = inputs.privKey
oops

2020-10-01 14:39 UTC, benthecarman approved these changes

2020-10-01 14:40 UTC, merged