Decode PSBT function
bitcoin-s/bitcoin-s pull request #2237
Opened 2020-11-03 22:48 UTC by benthecarman

Part of #2222 

Refactored and moved the `SeralizedTransaction` stuff so it could be used for the PSBT decoder and so it can all be in app commons.

2020-11-05 13:40 UTC, Christewart approved these changes

2020-11-05 13:41 UTC, Christewart requested changes
I don't see any unit tests?

2020-11-05 19:59 UTC, Christewart commented
```
./bitcoin-s-cli decodepsbt cHNidP8BAHECAAAAAaPTWHbUU9qZH3E8kIkbibcteaNNTH6csUa+pkkyrqdQAAAAAAD+////AgCHkwMAAAAAFgAU0vJ6xEpYLZgq0XT4Lxnrz3UcBhsAWmICAAAAABYAFMwT65eVs7MNdEmZ8a/btlp3iIuzAAAAAAABAP1AAQIAAAAFKZIoajB5IH5z9iHokxOlX2rQhwgcCyzaDPXXWbR1tJoAAAAAAP////9pTi0Pa6WrpNiaA3pqZ+YBse+v1jgpHtTzZy/vQHF0gkYAAAAA/////xfvpgcSWII60dKIxuOFbZoOZXgEMzh46FPKi3ciQ76kNwAAAAD//////mFLtbzVbA5rw0pzjzJPZP2fFf8+hHcPx/DsUmw9zSdRAAAAAP/////aFYTyhqQ1D5+3KyYhJklDPVsM7TZ5ckF+Ki2GCREY6TwAAAAA/////wOa5/UFAAAAACIAIPrv3JDIVLeft5JpaP948L/cyobLz9N9fzvM5qNeV34tLGwhAQAAAAAWABQyQn7LBTqGwlw1YR4czWqI99wxNk9PLAAAAAAAFgAUmp9tVa99KP5hNYiVoqw9Q20ISukAAAAAAQErmuf1BQAAAAAiACD679yQyFS3n7eSaWj/ePC/3MqGy8/TfX87zOajXld+LSICAnuk3VLqOOGKWaQyBUAiA0Dkh9fJlvN+voAZ2YE4q6lGRzBEAiBgJOvBFUyD1zFe1cCUi7Q+mabqnDPGwgJMVUzTM+9sqgIgYHaAZKgPoEzzDEc3RZYG1Sxsb4n3eM9OEwpaQaWieTABAQVHUiEDgsVFqH1kh8VRENc3ORR0Nyf7G4DuBuTJxi4ln6dRMTMhAnuk3VLqOOGKWaQyBUAiA0Dkh9fJlvN+voAZ2YE4q6lGUq4AAAA=

{
  "global": {
    "tx": {
      "txid": "116acd262033f1aefe57d93c97c6d47137438ac692d21242026ae7c5e55fc8f8",
      "version": 2,
      "size": 113,
      "vsize": 113,
      "weight": 452,
      "locktime": 0,
      "vin": [
        {
          "txid": "50a7ae3249a6be46b19c7e4c4da3792db7891b89903c711f99da53d47658d3a3",
          "hex": "a3d35876d453da991f713c90891b89b72d79a34d4c7e9cb146bea64932aea7500000000000feffffff",
          "vout": 0,
          "scriptSig": [
            
          ],
          "sequence": 4294967294
        }
      ],
      "vout": [
        {
          "value": 60000000,
          "n": 0,
          "scriptPubKey": [
            "OP_0",
            "BytesToPushOntoStackImpl(20)",
            "ByteVector(20 bytes, 0xd2f27ac44a582d982ad174f82f19ebcf751c061b)"
          ],
          "hex": "0087930300000000160014d2f27ac44a582d982ad174f82f19ebcf751c061b"
        },
        {
          "value": 40000000,
          "n": 1,
          "scriptPubKey": [
            "OP_0",
            "BytesToPushOntoStackImpl(20)",
            "ByteVector(20 bytes, 0xcc13eb9795b3b30d744999f1afdbb65a77888bb3)"
          ],
          "hex": "005a620200000000160014cc13eb9795b3b30d744999f1afdbb65a77888bb3"
        }
      ]
    },
    "version": 0,
    "unknowns": [
      
    ]
  },
  "inputs": [
    {
      "nonWitnessUtxo": {
        "txid": "50a7ae3249a6be46b19c7e4c4da3792db7891b89903c711f99da53d47658d3a3",
        "version": 2,
        "size": 320,
        "vsize": 320,
        "weight": 1280,
        "locktime": 0,
        "vin": [
          {
            "txid": "9ab475b459d7f50cda2c0b1c0887d06a5fa51393e821f6737e2079306a289229",
            "hex": "2992286a3079207e73f621e89313a55f6ad087081c0b2cda0cf5d759b475b49a0000000000ffffffff",
            "vout": 0,
            "scriptSig": [
              
            ],
            "sequence": 4294967295
          },
          {
            "txid": "82747140ef2f67f3d41e2938d6afefb101e6676a7a039ad8a4aba56b0f2d4e69",
            "hex": "694e2d0f6ba5aba4d89a037a6a67e601b1efafd638291ed4f3672fef407174824600000000ffffffff",
            "vout": 70,
            "scriptSig": [
              
            ],
            "sequence": 4294967295
          },
          {
            "txid": "a4be4322778bca53e87838330478650e9a6d85e3c688d2d13a82581207a6ef17",
            "hex": "17efa6071258823ad1d288c6e3856d9a0e657804333878e853ca8b772243bea43700000000ffffffff",
            "vout": 55,
            "scriptSig": [
              
            ],
            "sequence": 4294967295
          },
          {
            "txid": "27cd3d6c52ecf0c70f77843eff159ffd644f328f734ac36b0e6cd5bcb54b61fe",
            "hex": "fe614bb5bcd56c0e6bc34a738f324f64fd9f15ff3e84770fc7f0ec526c3dcd275100000000ffffffff",
            "vout": 81,
            "scriptSig": [
              
            ],
            "sequence": 4294967295
          },
          {
            "txid": "e9181109862d2a7e41727936ed0c5b3d43492621262bb79f0f35a486f28415da",
            "hex": "da1584f286a4350f9fb72b26212649433d5b0ced367972417e2a2d86091118e93c00000000ffffffff",
            "vout": 60,
            "scriptSig": [
              
            ],
            "sequence": 4294967295
          }
        ],
        "vout": [
          {
            "value": 100001690,
            "n": 0,
            "scriptPubKey": [
              "OP_0",
              "BytesToPushOntoStackImpl(32)",
              "ByteVector(32 bytes, 0xfaefdc90c854b79fb7926968ff78f0bfdcca86cbcfd37d7f3bcce6a35e577e2d)"
            ],
            "hex": "9ae7f50500000000220020faefdc90c854b79fb7926968ff78f0bfdcca86cbcfd37d7f3bcce6a35e577e2d"
          },
          {
            "value": 18967596,
            "n": 1,
            "scriptPubKey": [
              "OP_0",
              "BytesToPushOntoStackImpl(20)",
              "ByteVector(20 bytes, 0x32427ecb053a86c25c35611e1ccd6a88f7dc3136)"
            ],
            "hex": "2c6c21010000000016001432427ecb053a86c25c35611e1ccd6a88f7dc3136"
          },
          {
            "value": 2903887,
            "n": 2,
            "scriptPubKey": [
              "OP_0",
              "BytesToPushOntoStackImpl(20)",
              "ByteVector(20 bytes, 0x9a9f6d55af7d28fe61358895a2ac3d436d084ae9)"
            ],
            "hex": "4f4f2c00000000001600149a9f6d55af7d28fe61358895a2ac3d436d084ae9"
          }
        ]
      },
      "witnessUtxo": {
        "value": 100001690,
        "n": 0,
        "scriptPubKey": [
          "OP_0",
          "BytesToPushOntoStackImpl(32)",
          "ByteVector(32 bytes, 0xfaefdc90c854b79fb7926968ff78f0bfdcca86cbcfd37d7f3bcce6a35e577e2d)"
        ],
        "hex": "9ae7f50500000000220020faefdc90c854b79fb7926968ff78f0bfdcca86cbcfd37d7f3bcce6a35e577e2d"
      },
      "signatures": [
        {
          "pubkey": "027ba4dd52ea38e18a59a4320540220340e487d7c996f37ebe8019d98138aba946",
          "signature": "304402206024ebc1154c83d7315ed5c0948bb43e99a6ea9c33c6c2024c554cd333ef6caa022060768064a80fa04cf30c4737459606d52c6c6f89f778cf4e130a5a41a5a2793001"
        }
      ],
      "witScript": [
        "OP_2",
        "BytesToPushOntoStackImpl(33)",
        "ByteVector(33 bytes, 0x0382c545a87d6487c55110d7373914743727fb1b80ee06e4c9c62e259fa7513133)",
        "BytesToPushOntoStackImpl(33)",
        "ByteVector(33 bytes, 0x027ba4dd52ea38e18a59a4320540220340e487d7c996f37ebe8019d98138aba946)",
        "OP_2",
        "OP_CHECKMULTISIG"
      ],
      "unknowns": [
        
      ]
    }
  ],
  "outputs": [
    {
      "unknowns": [
        
      ]
    },
    {
      "unknowns": [
        
      ]
    }
  ]
}

```

What are the `"outputs": [ {"unknowns" : []}, ... ]` 

at the end of this?

2020-11-05 21:08 UTC, benthecarman commented
> What are the "outputs": [ {"unknowns" : []}, ... ] at the end of this?

Any of the maps can have unknown record, this is just to show the output maps are empty

2020-11-06 12:56 UTC, Christewart approved these changes

2020-11-06 12:56 UTC, merged