Fail broadcasting transaction when disconnected
bitcoin-s/bitcoin-s pull request #2336
Opened 2020-12-07 19:16 UTC by benthecarman

Fixes #2336

2020-12-07 19:19 UTC, benthecarman commented on node-test/src/test/scala/org/bitcoins/node/BroadcastTransactionTest.scala
> +    withSpvNodeConnectedToBitcoind(test, Some(BitcoindVersion.V17))
Needed to do this because of #2337

2020-12-08 14:58 UTC, Christewart requested changes
I've restarted CI a couple of times but this seems to fail consistently: 

https://github.com/bitcoin-s/bitcoin-s/runs/1517833592#step:5:630

2020-12-11 12:51 UTC, Christewart approved these changes

2020-12-11 14:12 UTC, Christewart commented
More failures on `BroadcastTransactionTest` 

https://github.com/bitcoin-s/bitcoin-s/pull/2336/checks?check_run_id=1537298211#step:5:518

https://github.com/bitcoin-s/bitcoin-s/pull/2336/checks?check_run_id=1537298243#step:5:844

2020-12-17 19:26 UTC, Christewart commented on node-test/src/test/scala/org/bitcoins/node/DisconnectedPeerTest.scala
> +      node.broadcastTransaction(tx)
isn't this always going to trivially fail, since the tx we are referencing isn't valid to the peers utxo set ?

2020-12-17 19:27 UTC, Christewart approved these changes

2020-12-17 19:28 UTC, merged