Update dlc before release
bitcoin-s/bitcoin-s pull request #2543
Opened 2021-01-21 07:55 UTC by nkohen

Built on top of #2516

2021-01-21 20:05 UTC, benthecarman commented
Has rebase issues

2021-01-22 19:32 UTC, benthecarman commented on app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/ViewDLCDialog.scala
> +                })
this is my bad but can use `NumericContractDescriptor.flip` here

2021-01-22 19:32 UTC, benthecarman commented on core/src/main/scala/org/bitcoins/core/protocol/dlc/OracleInfo.scala
> +            .isInstanceOf[EnumEventDescriptorV0TLV],
Maybe eventually we will want to make things like `OracleAnnouncementWithEnumTLV` so we don't need these

2021-01-22 19:32 UTC, benthecarman commented
Otherwise LGTM

2021-01-22 20:00 UTC, benthecarman approved these changes

2021-01-25 15:10 UTC, Christewart requested changes
So this is going to take multiple rounds or review, but I do feel strongly about getting more structure around `CETCalculator`. There is a lot of `Vector[Vector[]]` or even `Vector[Vector[Vector[]]]`.

It would really help me code review if these had useful names (and can we apply to invariants to any of these things??) to better understand what is happening.

2021-01-25 15:10 UTC, Christewart commented on app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCTableView.scala
> +        ) // FIXME
ping

2021-01-25 15:10 UTC, Christewart commented on app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCTableView.scala
> +        ) // FIXME
ping

2021-01-25 15:10 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/dlc/CETCalculator.scala
> +      numOracles: Int): Vector[Vector[Vector[Int]]] = {
So can we get some types for this stuff? I can't be the only one to think `Vector[Vector[Vector[Int]]]` is unreasonable to try and understand.

2021-01-25 15:10 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/dlc/CETCalculator.scala
> +      numOracles: Int): Vector[(Vector[Vector[Int]], Satoshis)] = {
>Vector[(Vector[Vector[Int]], Satoshis)] 

is also really hard to understand

2021-01-25 18:47 UTC, nkohen commented on app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCTableView.scala
> +        ) // FIXME
cc @benthecarman

2021-01-25 18:47 UTC, nkohen commented on app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCTableView.scala
> +        ) // FIXME
cc @benthecarman

2021-01-25 19:34 UTC, nkohen commented on core/src/main/scala/org/bitcoins/core/protocol/dlc/CETCalculator.scala
> +      numOracles: Int): Vector[Vector[Vector[Int]]] = {
Better?

2021-01-25 19:34 UTC, nkohen commented on core/src/main/scala/org/bitcoins/core/protocol/dlc/CETCalculator.scala
> +      numOracles: Int): Vector[(Vector[Vector[Int]], Satoshis)] = {
Better?

2021-02-02 14:13 UTC, Christewart commented on testkit/src/main/scala/org/bitcoins/testkit/core/gen/TLVGen.scala
> +        EnumContractDescriptor) = {
nit: return type

2021-02-02 14:14 UTC, Christewart approved these changes

2021-02-02 14:14 UTC, merged