Implement bech32m
bitcoin-s/bitcoin-s pull request #2572
Opened 2021-01-27 03:58 UTC by benthecarman

Built on top of #2571 

Implements bech32 in accordance to https://github.com/sipa/bips/blob/bip-bech32m/bip-bech32m.mediawiki 

This shouldn't be merged until the BIP is in a more final state.

2021-02-11 16:17 UTC, Christewart requested changes
So what are your thoughts on merging this? Should we wait until we have `WitnessScriptPubKeyV1` available to us ?

If i understand this, that would mean doing Tapscript/Taproot integration?

2021-02-11 16:17 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/Address.scala
> +  override def scriptPubKey: WitnessScriptPubKey = {
Doesn't this have to be a `WitnessScriptPubKeyV1`? 

I guess we don't have that now, but my understanding is v0 will always use the old bech32 encoding?

2021-02-11 16:17 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/Address.scala
> +  override def scriptPubKey: WitnessScriptPubKey = {
ah i see below, we should probably add a TODO or file an issue

2021-02-11 16:17 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/util/Bech32.scala
> +sealed abstract class Bech32Encoding {
add a link to what/where these differences are specified. I'm assuming they are on in the BIP?

2021-02-11 16:17 UTC, Christewart commented on core-test/src/test/scala/org/bitcoins/core/protocol/Bech32mSpec.scala
> +class Bech32mSpec extends Properties("Bech32mSpec") {
nit: This is the old style of test cases (uses scalacheck, not scalatest). We are trying to slowly move away from these over the long term. Can you write these using `BitcoinSUnitTest` ? Also convert the `Bech32Spec` file if you are feeling ambitious :-)

2021-02-11 16:17 UTC, Christewart commented on core-test/src/test/scala/org/bitcoins/core/protocol/Bech32mSpec.scala
> +class Bech32mSpec extends Properties("Bech32mSpec") {
https://github.com/bitcoin-s/bitcoin-s/blob/c5be81d5e21cd22a4e69dc86dcf47fbaa7d623f3/core-test/src/test/scala/org/bitcoins/core/protocol/AddressTest.scala#L12

2021-02-11 16:17 UTC, Christewart commented on core-test/src/test/scala/org/bitcoins/core/protocol/Bech32mSpec.scala
> +class Bech32mSpec extends Properties("Bech32mSpec") {
I guess this means this file can be deleted and test cases migrated to `Bech32mTest`

2021-02-16 15:00 UTC, Christewart approved these changes
So this LGTM, 

but is BIP350 actually finalized? Is it deployed as part of bitcoin core 0.21.0? It seems to me this shouldn't be merged until the spec is finalized ? 

https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki

2021-02-16 15:43 UTC, benthecarman commented
> So this LGTM,
> 
> but is BIP350 actually finalized? Is it deployed as part of bitcoin core 0.21.0? It seems to me this shouldn't be merged until the spec is finalized ?
> 
> [bitcoin/bips@`master`/bip-0350.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki)

The spec should be finalized, it is not merged into core yet: https://github.com/bitcoin/bitcoin/pull/20861

imo this should be fine to merge though

2021-02-17 12:09 UTC, Christewart commented
> > So this LGTM,
> > but is BIP350 actually finalized? Is it deployed as part of bitcoin core 0.21.0? It seems to me this shouldn't be merged until the spec is finalized ?
> > [bitcoin/bips@`master`/bip-0350.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki)
> 
> The spec should be finalized, it is not merged into core yet: [bitcoin/bitcoin#20861](https://github.com/bitcoin/bitcoin/pull/20861)
> 
> imo this should be fine to merge though

I vote to wait until it gets merged into core as there is less likely to be changes after that occurs

2021-03-18 23:04 UTC, merged