Add github workflow steps to publish to dockerhub
bitcoin-s/bitcoin-s pull request #2684
Opened 2021-02-18 20:38 UTC by Christewart

This PR attempts to follow this guide to publish docker images on every CI merge and tag push

https://docs.docker.com/ci-cd/github-actions/

I've added the appropriate github secrets, so this _should_ work :tm:

I doubt I got this right on the first try, but i don't know if there is a way to debug without merging? 

Docker repos where images are published too:

https://hub.docker.com/repository/docker/bitcoinscala/bitcoin-s-server

https://hub.docker.com/repository/docker/bitcoinscala/bitcoin-s-oracle-server

2021-02-18 20:41 UTC, benthecarman requested changes

2021-02-18 20:41 UTC, benthecarman commented on .github/workflows/docker-publish.yml
> +    tags: ["*"]
this should be

```
  push:
    branches: [master, main, adaptor-dlc]
    tags: ["*"]
```

2021-02-19 15:47 UTC, Christewart commented
Ok this should be good to go. Unfortunately you can test things that access github secrets on the main repo as a PR (I can just do `echo $SUPER_SECRET_VAR` in a PR build script).

So I had to push the origin repo and test it out on this branch: 

https://github.com/bitcoin-s/bitcoin-s/tree/2021-02-18-github-docker-workflow

You can see the last commit is 2b80907 

and you can see the docker hub image published here: 

https://hub.docker.com/layers/138281713/bitcoinscala/bitcoin-s-server/0.5.0-41-2b80907c-SNAPSHOT/images/sha256-bfc7893f68e182cdbb7d007ebe84de61852142e4045adbeed9c25422ebfddbaa?context=explore

https://hub.docker.com/layers/bitcoinscala/bitcoin-s-oracle-server/0.5.0-41-2b80907c-SNAPSHOT/images/sha256-bfe36b5e507f2a6ef1b5b850333beab2e3d4e581328decbd23d3bb6466dd8a37?context=explore

2021-02-19 15:54 UTC, benthecarman approved these changes

2021-02-19 16:09 UTC, merged