2021 04 24 bitcoin s scripts
bitcoin-s/bitcoin-s pull request #2961
Opened 2021-04-24 15:31 UTC by Christewart

This adds a dedicated bitcoin-s scripts project. This is meant to be a place to place useful utilities for running occasionally against bitcoin-s. 

There are two scripts to stat
1. `ScanBitcoind` - scan against bitcoind between a height range
2. `ZipDatadir` - Zip's the bitcoin-s datadir 

As an example, here is the result of `ScanBitcoind` when counting segwit txs between `675,000-tip`

>Count of segwit txs from height675000 to endHeight=680427 is 5707220. It took 335069ms

2021-04-24 23:18 UTC, benthecarman requested changes

2021-04-24 23:18 UTC, benthecarman commented on app/scripts/src/main/scala/org/bitcoins/scripts/ZipDatadir.scala
> +//import java.nio.file.Path
Ping

2021-04-24 23:18 UTC, benthecarman commented on app/scripts/src/main/scala/org/bitcoins/scripts/ScanBitcoind.scala
> +      counter
I think you can do `block.transactions.count(_.isInstanceOf[WitnessTransaction])`

2021-04-25 15:38 UTC, Christewart commented
How long it took to scan testnet with #2963 

>Count of segwit txs from height=1 to endHeight=1972660 is 14248115. It took 2665709ms

2021-04-25 18:18 UTC, benthecarman approved these changes

2021-04-25 19:03 UTC, merged