Fix verify funding sigs
bitcoin-s/bitcoin-s pull request #3194
Opened 2021-05-28 20:24 UTC by benthecarman

2021-05-28 20:43 UTC, Christewart requested changes
Any explanation why this is wrong or a unit test tot prevent regression?

2021-05-28 20:46 UTC, benthecarman commented
> Any explanation why this is wrong or a unit test tot prevent regression?

Updated description

2021-05-28 22:51 UTC, Christewart approved these changes

2021-05-29 00:07 UTC, Christewart commented
Compiler error: https://github.com/bitcoin-s/bitcoin-s/pull/3194/checks?check_run_id=2698586340#step:5:230

2021-05-29 00:59 UTC, merged