SOCKS5 client transport
bitcoin-s/bitcoin-s pull request #3396
Opened 2021-07-12 22:29 UTC by rorp

2021-07-13 14:52 UTC, Christewart requested changes

2021-07-13 14:52 UTC, Christewart commented on tor-test/src/test/scala/org/bitcoins/tor/Socks5ClientTransportSpec.scala
> +  ignore("connect to real daemon") {
This works locally I presume?

2021-07-13 14:52 UTC, Christewart commented on tor-test/src/test/scala/org/bitcoins/tor/Socks5ClientTransportSpec.scala
> +    extends TestKit(ActorSystem("test"))
It would be nice if we could figure out a way to get this all to hook into our existing test harnesses (`BitcoinSAsyncTest` or `BitcoinSUnitTest`). Likely we do need a new trait, but if we start doing more actor/stream programming, we will want a common test trait

2021-07-13 14:52 UTC, Christewart commented on tor/src/main/scala/org/bitcoins/tor/Socks5Connection.scala
> +    parseAuth(data)
Is this just being dropped on the floor? It would be nice to do something with the return type even if it is just throwing an error. 

For instance, if we change the behavior of `parseAuth()` in the future to not throw exceptions, we will never get a compiler error. I also don't think we have a unit test for this behavior?

2021-07-13 14:52 UTC, Christewart commented on tor/src/main/scala/org/bitcoins/tor/Socks5Connection.scala
> +        case _ => throw Socks5Error(s"Unrecognized address type")
nit: Add the byte to the error message for easier debugging.

```scala
case b => throw Socks5Error(s"Unrecognized address type=$b")
```

2021-07-13 14:52 UTC, Christewart commented on tor/src/main/scala/org/bitcoins/tor/Socks5Connection.scala
> +  def parseGreetings(data: ByteString, passwordAuth: Boolean): Byte = {
Do you have any references to the SOCKS5 specification you could link a scaladoc for future users of the code? I'm not sure where these magic bytes are coming from.

2021-07-13 14:52 UTC, Christewart commented on tor/src/main/scala/org/bitcoins/tor/Socks5Connection.scala
> +    parseAuth(data)
Even a class level scaladoc on `class Socks5Connection` would be very helpful.

2021-07-13 14:52 UTC, Christewart commented on tor/src/main/scala/org/bitcoins/tor/Socks5ClientTransport.scala
> +            Try(parseGreetings(data, credentialsOpt.nonEmpty)) match {
maybe just worth returning a `Try[]` from `parseGreetings`?

2021-07-19 11:34 UTC, Christewart approved these changes

2021-07-19 11:34 UTC, Christewart commented
@benthecarman does this look to you?

2021-07-19 15:36 UTC, benthecarman approved these changes

2021-07-19 15:36 UTC, benthecarman commented on tor-test/src/test/scala/org/bitcoins/tor/Socks5ClientTransportSpec.scala
> +    assume(torEnabled, "TOR environment variable is not set")
Why `assume` and not `assert`?

2021-07-19 15:36 UTC, benthecarman commented on tor-test/src/test/scala/org/bitcoins/tor/Socks5ClientTransportSpec.scala
> +          "http://explorerzydxu5ecjrkwceayqybizmpjjznk5izmitf2modhcusuqlid.onion/"),
maybe worth eventually switching this to our own sites

2021-07-19 17:55 UTC, merged