Made relay flag in version message configurable
bitcoin-s/bitcoin-s pull request #3416
Opened 2021-07-17 11:09 UTC by shruthii625

'relay' is set to false by default.
If we want to change it, we can go to the bitcoin-s.conf file and set it to true. When set to true, we see that the transaction messages get logged.

2021-07-17 12:06 UTC, Christewart commented
Looks like there is compile issues: https://github.com/bitcoin-s/bitcoin-s/pull/3416/checks?check_run_id=3092924515#step:5:190

2021-07-17 12:14 UTC, shruthii625 commented
> Looks like there is compile issues: https://github.com/bitcoin-s/bitcoin-s/pull/3416/checks?check_run_id=3092924515#step:5:190

oops, I'll check it

2021-07-17 12:15 UTC, Christewart commented
> > Looks like there is compile issues: https://github.com/bitcoin-s/bitcoin-s/pull/3416/checks?check_run_id=3092924515#step:5:190
> 
> oops, I'll check it

I'm hoping on your next commit CI automatically gets run, I need to figure out how to adjust the settings so that you and @shreyanshyad don't need me to manually approve CI runs :/

2021-07-18 21:38 UTC, Christewart requested changes
Works for me! 🎉 We just have to add a few more things

You need to modify the [example configuration file that we publish on our website](https://bitcoin-s.org/docs/config/configuration#example-configuration-file). 

The idea for this page is to show all the available options to configure bitcoin-s in one place, with their defaults. you need to add the `bitcoin-s.node.relay=false` configuration to this file 

https://github.com/bitcoin-s/bitcoin-s/blob/8b663d91b647e8e22e4ee1a4f6cd976b00c6a766/docs/config/configuration.md#L156

Specifically you need to add 

```
bitcoin-s { 
   node { 
        relay = false
    }
}
```

Once we get these final changes in, we can merge your first PR 🎉

2021-07-18 21:38 UTC, Christewart commented on node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
> +              logger.debug(
lets revert these too

2021-07-18 21:38 UTC, Christewart commented on app/server/src/main/resources/logback.xml
> +    <logger name="org.bitcoins.node.networking.peer.PeerMessageReceiver" level="DEBUG"/>
Please revert these for actually merging into master

2021-07-18 21:38 UTC, Christewart commented on node/src/main/scala/org/bitcoins/node/config/NodeAppConfig.scala
> +    if (config.hasPath("bitcoin-s.node.relay"))(config.getBoolean(
let's clean up the format here. Scala gives you a lot of optionality with syntax, but it is 99% of the time best to use braces. 

```scala
if (config.hasPath("bitcoin-s.node.relay")) {
  config.getBoolean("bitcoin-s.node.relay")
} else {
  false
}

2021-07-19 12:03 UTC, Christewart approved these changes

2021-07-19 14:56 UTC, benthecarman approved these changes

2021-07-19 14:59 UTC, merged