CI fixes
bitcoin-s/bitcoin-s pull request #3597
Opened 2021-08-24 15:59 UTC by rorp

2021-08-24 16:04 UTC, benthecarman requested changes

2021-08-24 16:04 UTC, benthecarman commented on .github/workflows/Linux_2.12_Node_Tests.yml
> +name: Linux 2.12 App, Chain, Node, and Core Tests
should rename

2021-08-24 16:04 UTC, benthecarman commented on .github/workflows/Linux_2.13_Node_Tests.yml
> +name: Linux 2.13 App, Chain, Node, and Core Tests
Same here

2021-08-24 16:33 UTC, benthecarman approved these changes

2021-08-24 16:33 UTC, benthecarman requested changes
Compile Failing

2021-08-24 19:18 UTC, benthecarman commented on node/src/main/scala/org/bitcoins/node/Node.scala
> +                                              maxTries = 240,
This will make the tor tests much more flaky, maybe bump it up but only when tor is enabled

2021-08-25 20:06 UTC, Christewart approved these changes

2021-08-25 20:07 UTC, merged