Use random ports for pre-packaged Tor daemon
bitcoin-s/bitcoin-s pull request #3604
Opened 2021-08-25 17:09 UTC by rorp

2021-08-25 17:12 UTC, benthecarman commented on tor/src/main/scala/org/bitcoins/tor/config/TorAppConfig.scala
> +  private lazy val ports = {
should probably make these `def`s so if we spin up multiple tor instances they don't overlap

2021-08-25 17:27 UTC, rorp commented on tor/src/main/scala/org/bitcoins/tor/config/TorAppConfig.scala
> +  private lazy val ports = {
Let's do it when we need multiple instances.

2021-08-25 20:32 UTC, Christewart commented on db-commons/src/main/resources/reference.conf
> +    use-random-ports = true
So when we ship our binaries, by default we should have this on i think? 

https://github.com/bitcoin-s/bitcoin-s/blob/4ef1e6bcb617c161818b58fcffc470fac3e28c4c/app/bundle/src/main/resources/application.conf#L14

2021-08-25 20:32 UTC, Christewart commented on testkit/src/main/scala/org/bitcoins/testkit/BitcoinSTestAppConfig.scala
> +         |  tor.use-random-ports = false
Shouldn't we be using random ports in tests?

2021-08-25 20:36 UTC, rorp commented on db-commons/src/main/resources/reference.conf
> +    use-random-ports = true
It's already enabled in `reference.conf`

2021-08-25 20:39 UTC, rorp commented on testkit/src/main/scala/org/bitcoins/testkit/BitcoinSTestAppConfig.scala
> +         |  tor.use-random-ports = false
We could, but the tests running in parallel wouldn't be able reuse a single tor instance.

`Socks5ClientTransportSpec` runs with `tor.use-random-ports = true` thought.

2021-08-26 13:10 UTC, Christewart requested changes
This does not seem to work with `bundle/run` on either neutrino backends or bitcoind backends on e1d9fa8

Here is my stack trace for an attempt to connect on neutrino via tor

>[info] Aug 26 08:08:33.357 [notice] Opened Control listener connection (ready) on 127.0.0.1:17137
[info] 2021-08-26T13:09:33UTC ERROR [BitcoinSServerMain] Failed to startup server!
[info] org.bitcoins.asyncutil.AsyncUtil$RpcRetryException: Condition timed out after 60 attempts with interval=1 second waiting periods
[info]  at org.bitcoins.tor.config.TorAppConfig.isBinaryFullyStarted(TorAppConfig.scala:166)
[info]  at org.bitcoins.tor.config.TorAppConfig.$anonfun$start$2(TorAppConfig.scala:129)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[info] 2021-08-26T13:09:33UTC ERROR [BitcoinSServerMain] Failed to initialize configuration for BitcoinServerMain
[info] org.bitcoins.asyncutil.AsyncUtil$RpcRetryException: Condition timed out after 60 attempts with interval=1 second waiting periods
[info]  at org.bitcoins.tor.config.TorAppConfig.isBinaryFullyStarted(TorAppConfig.scala:166)
[info]  at org.bitcoins.tor.config.TorAppConfig.$anonfun$start$2(TorAppConfig.scala:129)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

2021-08-26 18:02 UTC, Christewart approved these changes

2021-08-26 18:02 UTC, merged