Decode DLC messages cli commands
bitcoin-s/bitcoin-s pull request #3636
Opened 2021-08-30 19:28 UTC by benthecarman

Adds 3 commands

`decodeoffer`

`decodeannouncement`

`decodeattestments`

2021-08-31 15:17 UTC, user411 approved these changes

2021-08-31 18:11 UTC, Christewart requested changes
Can we add examples to the site for this? Sort of related to #3631

https://github.com/discreetlogcontracts/dlcspecs/pull/150

2021-09-02 14:13 UTC, Christewart commented
needs rebase

2021-09-03 14:46 UTC, Christewart approved these changes

2021-09-03 14:46 UTC, merged