Store oracle name in the database
bitcoin-s/bitcoin-s pull request #3748
Opened 2021-10-13 03:55 UTC by rorp

2021-10-13 13:16 UTC, Christewart requested changes

2021-10-13 13:16 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/crypto/ExtKey.scala
> +  def name: Option[String]
The `ExtKey` is meant to follow the bip32 spec, there is no `name` in the bip32 spec 

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

Perhaps we can just wrap a key and then change the type in `MasterXPubDAO`? 

I.e. 

```scala
case class MasterXPubKey(extKey: ExtKey, name: Option[String])
```

and then use that in `MasterXPubDAO`?

2021-10-14 12:12 UTC, Christewart approved these changes

2021-10-14 14:28 UTC, user411 approved these changes

2021-10-14 14:35 UTC, merged