Initial c-lightning rpc support
bitcoin-s/bitcoin-s pull request #3755
Opened 2021-10-15 09:17 UTC by benthecarman

Adds initial support for making c-lightning rpc requests

2021-10-15 12:26 UTC, Christewart commented
needs rebase

2021-10-17 14:25 UTC, benthecarman commented
CI passing now, should be good for review :)

2021-10-19 14:04 UTC, Christewart requested changes

2021-10-19 14:04 UTC, Christewart commented on clightning-rpc/src/main/scala/com/bitcoins/clightning/rpc/CLightningUnixSocketHandler.scala
> +  // -- below cribbed from https://github.com/clightning4j/JRPClightning/blob/7e1708d7ed67511ab5e67e9f4bc103d6b2c5be32/src/main/java/jrpc/service/socket/UnixDomainSocketRpc.java
Is there not a dependency that can handle this?

2021-10-19 14:04 UTC, Christewart commented on clightning-rpc/src/main/scala/com/bitcoins/clightning/rpc/config/CLightningInstance.scala
> +object CLightningInstance
`CLightningInstanceLocal` ?

2021-10-19 14:04 UTC, Christewart commented on clightning-rpc/src/main/scala/com/bitcoins/clightning/rpc/config/CLightningInstance.scala
> +case class CLightningInstance(
Can we call that `CLightningInstanceLocal` if I understand correctly. We can add the remote later if it is needed?

2021-10-19 14:04 UTC, Christewart commented on core/src/main/scala/org/bitcoins/core/protocol/ln/channel/ShortChannelId.scala
> +            "ShortChannelId: invalid block height")
at the invalid things in the error message so it is easier to debug if something goes wrong

2021-10-19 14:04 UTC, Christewart commented on project/Deps.scala
> +      "com.kohlschutter.junixsocket" % "junixsocket-core" % V.jUnixSocketV
interesting, are we sure this isn't handled by akka or netty or something like that?

2021-10-19 14:04 UTC, Christewart commented on testkit/src/main/scala/org/bitcoins/testkit/clightning/CLightningRpcTestUtil.scala
> +trait CLightningRpcTestUtil extends Logging {
Everything looks ok to me in this file, but in the future it would be nice to have a thin interface like `LnApi` or something that all our lightning rpc clients extend, so we don't have to re-write this for every implementation.

2021-10-19 14:04 UTC, Christewart commented on testkit/src/main/scala/org/bitcoins/testkit/fixtures/CLightningFixture.scala
> +          val actorSystemA =
Why new `ActorSystem`'s here? Also i don't see them getting shutdown in the tear down

2021-10-19 15:05 UTC, benthecarman commented on project/Deps.scala
> +      "com.kohlschutter.junixsocket" % "junixsocket-core" % V.jUnixSocketV
akka has something that I tried using but couldn't get it to work

2021-10-19 15:05 UTC, benthecarman commented on project/Deps.scala
> +      "com.kohlschutter.junixsocket" % "junixsocket-core" % V.jUnixSocketV
@rorp recommened to use this one to me

2021-10-19 15:07 UTC, benthecarman commented on clightning-rpc/src/main/scala/com/bitcoins/clightning/rpc/CLightningUnixSocketHandler.scala
> +  // -- below cribbed from https://github.com/clightning4j/JRPClightning/blob/7e1708d7ed67511ab5e67e9f4bc103d6b2c5be32/src/main/java/jrpc/service/socket/UnixDomainSocketRpc.java
AFUNIXSocketAddress is doing most of it

2021-10-19 15:17 UTC, benthecarman commented on testkit/src/main/scala/org/bitcoins/testkit/fixtures/CLightningFixture.scala
> +          val actorSystemA =
Was able to get rid of `ActorSystem`s inside of `CLightningRpcClient`

2021-10-19 15:27 UTC, benthecarman commented on project/Deps.scala
> +      "com.kohlschutter.junixsocket" % "junixsocket-core" % V.jUnixSocketV
CLightning is weird and doesn't have a standard json rpc server, you pipe in commands into a file using a unix socket

2021-10-19 15:28 UTC, Christewart commented
It seems to take 10 minutes to run the test suite locally. Each test case that uses the `lightningd` takes ~1 minute on my machine. Not sure why

![Screenshot from 2021-10-19 10-28-15](https://user-images.githubusercontent.com/3514957/137942781-b5cb61be-9ed3-4562-a427-6c23ba1860aa.png)

2021-10-19 15:33 UTC, benthecarman commented
> It seems to take 10 minutes to run the test suite locally. Each test case that uses the lightningd takes ~1 minute on my machine. Not sure why

I get the same thing. In testing it takes awhile for it to see blocks from bitcoind. I think it polls for blocks from bitcoind instead of using zmq so it is slower.

2021-10-19 15:55 UTC, Christewart commented
> > It seems to take 10 minutes to run the test suite locally. Each test case that uses the lightningd takes ~1 minute on my machine. Not sure why
> 
> I get the same thing. In testing it takes awhile for it to see blocks from bitcoind. I think it polls for blocks from bitcoind instead of using zmq so it is slower.

I'll file an issue to look into this later,  i don't think it necessarily needs to be solved now though

2021-10-19 15:57 UTC, Christewart approved these changes

2021-10-19 15:58 UTC, merged