2021 01 06 tlv invariants
bitcoin-s/bitcoin-s pull request #3965
Opened 2022-01-06 17:18 UTC by Christewart

Add invariants to various TLV data structures. Mainly around making sure `Vector`s aren't empty.

@nkohen and i discussed this might be a easy way to get to the bottom of #3869 as when we delete adaptor signatures from the database, we might end up have a `CETSignaturesTLV` that is empty. This gives us the opportunity to "fail-fast" and see the root cause of the issue (not having adaptor sigs).

I haven't tested this out yet on #3869, but this seems like a good idea to add regardless.

2022-01-06 17:47 UTC, benthecarman approved these changes

2022-01-06 18:15 UTC, nkohen requested changes
I'm not sure this will catch what we discussed, and also I don't think that it is necessarily good to have exceptions thrown at this level, the invariants should live on the deserialized versions not the serialized ones (for example, we could have places where we don't go through TLV when communicating between db and wallet). For example, an invariant should probably be on our internal DLCAccept and DLCSign types.

2022-01-06 18:40 UTC, Christewart commented
> I'm not sure this will catch what we discussed, and also I don't think that it is necessarily good to have exceptions thrown at this level, the invariants should live on the deserialized versions not the serialized ones (for example, we could have places where we don't go through TLV when communicating between db and wallet). For example, an invariant should probably be on our internal DLCAccept and DLCSign types.

That introduces just a few failures on 8186f14 :sweat_smile: 

![Screenshot from 2022-01-06 12-39-18](https://user-images.githubusercontent.com/3514957/148433932-eed77a7e-4d3b-4f28-bf6e-f5a1e8474474.png)

2022-01-06 19:22 UTC, Christewart commented
> > I'm not sure this will catch what we discussed, and also I don't think that it is necessarily good to have exceptions thrown at this level, the invariants should live on the deserialized versions not the serialized ones (for example, we could have places where we don't go through TLV when communicating between db and wallet). For example, an invariant should probably be on our internal DLCAccept and DLCSign types.
> 
> That introduces just a few failures on [8186f14](https://github.com/bitcoin-s/bitcoin-s/commit/8186f1409eaac4824883bcb62fd9400e4cf9b2a3) sweat_smile
> 
> ![Screenshot from 2022-01-06 12-39-18](https://user-images.githubusercontent.com/3514957/148433932-eed77a7e-4d3b-4f28-bf6e-f5a1e8474474.png)

Commenting out one line gets all the test cases too pass on 8186f14

https://github.com/bitcoin-s/bitcoin-s/blob/4ca586ca462cd0bf029cfe43f698d9e49da4aa6e/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala#L64

My understanding is this line deletes the adaptor signatures in the database. @benthecarman hypothesized this was the root cause of #3869 , still haven't been able to prove it yet but it could be related to this change.

I think i'm going to wrap `Vector[DLCCETSignaturesDb]` -> `Option[Vector[DLCCETSignaturesDb]]` so we have a typesafe way of representing when we do / do not have the cet sigs available to us.

https://github.com/bitcoin-s/bitcoin-s/blob/f71d3567ed21df6bb050ee184d6fe31b4369c654/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCDataManagement.scala#L319

2022-01-08 18:17 UTC, benthecarman reviewed
otherwise lgtm

2022-01-08 18:17 UTC, benthecarman commented on dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
> +                s"Could not find dlc associated with this contractId=${contractId}")
nit: call `.hex` on `contractId`

2022-01-08 18:17 UTC, benthecarman commented on dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
> +                s"If we don't have CET signatures, the closing tx must be defined, contractId=$contractId")
nit: call `.hex` on `contractId`

2022-01-08 18:17 UTC, benthecarman commented on dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
> +                s"Could not find closing tx for DLC in db, contactId=$contractId closingTxId=$closingTxId")
nit: call `.hex` on `contractId` and `closingTxId`

2022-01-08 18:17 UTC, benthecarman commented on dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCDataManagement.scala
> +      logger.info(s"outcomeSigs=$outcomeSigs dlcId=${dlcId.hex}")
`outcomeSigs` could be very large here, maybe make this a trace level log or simplify what it is printing

2022-01-08 18:17 UTC, benthecarman commented on dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala
> +              //just return the dlcdb given to us?
yeah this sounds correct

2022-01-08 22:21 UTC, merged