`getdlcoffer` RPC
bitcoin-s/bitcoin-s pull request #4166
Opened 2022-03-04 22:04 UTC by rorp

2022-03-05 16:18 UTC, Christewart commented
Does not compile

2022-03-05 16:25 UTC, Christewart requested changes
A unit test would be nice so we can detect future regressions if we ever accidentally break the API

2022-03-05 16:25 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
> +              val tlv = offer.toTLV
We return the `LnMessage(tlv)` here. We should probably be consistent and return the same format here too.

https://github.com/bitcoin-s/bitcoin-s/blob/9cfe65f1cca8e3a7df78e0c1d07866bfbe9a28da/app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala#L348

2022-03-07 20:14 UTC, Christewart approved these changes

2022-03-07 20:27 UTC, user411 approved these changes
This tests well for me

2022-03-07 20:28 UTC, merged