Update lots of deps
bitcoin-s/bitcoin-s pull request #4205
Opened 2022-03-21 21:23 UTC by benthecarman

2022-03-21 22:20 UTC, Christewart commented
What happened to scala-steward ? ☠️ ☠️. I think i would prefer to merge this after we cut 1.9.1 (https://github.com/bitcoin-s/bitcoin-s/projects/9) so we don't introduce any surprises just before releasing

2022-03-21 22:22 UTC, benthecarman commented
> Is there anything time sensitive for you in here?

Mainly just wanted the akka update

2022-04-19 12:31 UTC, Christewart requested changes

2022-04-19 12:31 UTC, Christewart commented on project/Deps.scala
> +    val pgEmbeddedV = "1.0.0"
This needs to be reverted. They are moving to a docker based postgres environment in the `1.x.x` series. We do not have that setup. 

https://github.com/opentable/otj-pg-embedded/issues/166

2022-04-19 12:31 UTC, Christewart commented on testkit/src/main/scala/org/bitcoins/testkit/EmbeddedPg.scala
> +    pg.map(_.getJdbcUrl("postgres"))
i'm guessing this will need to be reverted too?

2022-04-19 12:36 UTC, Christewart commented on project/Deps.scala
> +    val pgEmbeddedV = "1.0.0"
https://github.com/bitcoin-s/bitcoin-s/runs/5634927314?check_suite_focus=true#step:6:2672

2022-04-19 20:28 UTC, closed without merging