Tor v0.4.6.10
bitcoin-s/bitcoin-s pull request #4331
Opened 2022-05-11 03:29 UTC by rorp

2022-05-11 04:06 UTC, benthecarman requested changes
Need to update this as well

https://github.com/bitcoin-s/bitcoin-s/blob/6356a50a893a8b575762d8c70b65a569d967da7e/tor/src/main/scala/org/bitcoins/tor/client/TorClient.scala#L80

2022-05-11 10:13 UTC, Christewart commented
Why not upgrade to 0.4.7? https://blog.torproject.org/congestion-contrl-047/

2022-05-17 12:45 UTC, Christewart commented
> Why not upgrade to 0.4.7.x? https://blog.torproject.org/congestion-contrl-047/

Official binaries have not been published yet to the tor browser.

2022-05-17 17:06 UTC, Christewart approved these changes

2022-05-17 17:06 UTC, merged