DLC <-> contact mapping
bitcoin-s/bitcoin-s pull request #4346
Opened 2022-05-18 19:14 UTC by rorp

Creates a one-to-many relation between DLCs and contacts.

Add `dlc-contact-add` and `dlc-contact-remove` RPC calls to add and remove the associations.

`getdlc` and `getdlcs` RPC calls return JSON responses with associated contacts.

2022-05-23 15:28 UTC, user411 commented
I made an Offer to a peer on my Contact List using this branch (which they then accepted) and the contact field on the resulting DLC came back null. I would expect it to be populated automatically.

![Screen Shot 2022-05-23 at 9 27 40 AM](https://user-images.githubusercontent.com/22351459/169854221-ac7843f9-0616-4dd5-942c-a1eaae340c43.png)

2022-05-26 18:04 UTC, user411 commented
I notice DLC.contact can be null, a string, or a Contact object. I would prefer it was always the peer address string (contactId) or null. We could potentially call this field 'peer' vs 'contact' as it's the peer we're working with and we call it 'peer' in the IncomingOffer context.

2022-06-01 13:25 UTC, Christewart requested changes
Mostly just code re-organization, but @user411 's requested API level changes need to be addressed too.

2022-06-01 13:25 UTC, Christewart commented on dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/IncomingDLCOffersHandling.scala
> +      contcatId: InetSocketAddress): Future[Unit] = {
Why not just return the `DLCContactMappingDb` rather than `Unit`? That way we can actually do something with the returned value, especially if we every modify `ContactDb` in the future to be more than `dlcId` and `contcatId` ?

I don't think there is any reason `DLCContactMappingDb` can't be moved to `core`.

2022-06-01 13:25 UTC, Christewart commented on dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/models/DLCContactMappingDAO.scala
> +case class DLCContactMapping(dlc: DLCDb, contact: Option[DLCContactDb]) {
Move `DLCContactMapping` and `DLCContactMappingDb` to core

2022-06-06 14:12 UTC, user411 commented
In my testing, if an IncomingOffer has a peer that is not in the contacts list, the DLC.peer field does not come in with a value from `getdlcs`. We need that fields to populate so the user can later make a contact from their DLC. DLC.peer should not be keyed/indexed to the contacts address field. It should just be the Tor address for the counterparty of the DLC, null, or whatever the user has arbitrarily set.

2022-06-06 18:12 UTC, user411 commented
We should not be creating Contacts for users, we should be leaving the Tor DLC Host Address behind so they can create their own contacts from previous data as they like.

2022-06-09 15:54 UTC, user411 commented
Running on a261a7b, when I start up I get

```
[info] 2022-06-09T15:51:55UTC INFO [NodeAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@6a0b7489 migrations fro the node project
[info] 2022-06-09T15:51:55UTC ERROR [BitcoinSServerMain] Failed to startup server!
[info] org.flywaydb.core.api.FlywayException: Unable to baseline schema history table "main"."flyway_schema_history" as it already contains migrations
```

Any recommendation on getting around this? I ran this branch at several other points during its history.

2022-06-09 17:01 UTC, user411 commented
I deleted my dlcdb.sqlite to get past the last issue.

I started up, lost all contacts I had previously and of course DLCs. I made a fake contact then I sent a new offer over from another computer, and accepted it. Then I went to contacts and tried to create a contact for the address the offer came in from. I got the following:
![Screen Shot 2022-06-09 at 10 53 49 AM](https://user-images.githubusercontent.com/22351459/172903119-e39cb781-92ac-4055-af5b-54154a8dd656.png)

I previously had this address in use as a contact. Do I need to do more to reset my state? If the database really was destroyed, I wouldn't expect anything to get in the way of this keying - the contact doesn't exist yet according to the list received.

2022-06-13 18:35 UTC, user411 approved these changes

2022-06-13 18:38 UTC, Christewart approved these changes

2022-06-14 13:14 UTC, merged