Seed backup API
bitcoin-s/bitcoin-s pull request #4357
Opened 2022-06-01 02:22 UTC by rorp

2022-06-01 14:09 UTC, Christewart requested changes

2022-06-01 14:09 UTC, Christewart commented on key-manager/src/main/scala/org/bitcoins/keymanager/WalletStorage.scala
> +          case value: ujson.Value => Some(Try(value.num.toLong).get)
nit: I think `Try(value.num.toLong).toOption` works too

2022-06-01 14:09 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala
> +        throw new IllegalArgumentException("password must be a string or null")
nit: Always nice to add the input to the error message for ease of debugging

i.e.

```scala
      case x @ (Arr(_) | False | True | Num(_) | Obj(_)) =>
        throw new IllegalArgumentException(s"password must be a string or null, got=$x")
```

now the error message will contain the input.

2022-06-01 14:09 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala
> +        throw new IllegalArgumentException(s"Expected json.Arr")
same here, would be nice to put the thing we got (`v: Value`) in the error message.

2022-06-01 14:09 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
> +            val seedPath = kmConf.seedFolder.resolve(
This pattern is used in a ton of places, can we refactor this to a helper method somewhere?

2022-06-01 14:09 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
> +            Server.httpSuccess(ujson.Null)
Why not use the `"ok"` response we use elsewhere?

2022-06-01 14:09 UTC, Christewart commented on key-manager/src/main/scala/org/bitcoins/keymanager/WalletStorage.scala
> +                case Some(_) => () // ignore
Maybe a 

```
logger.warn(s"Seed has already been backed up, ignorning new request to mark it as backed up")
``` 

here that the seed has already been backup?

2022-06-01 14:29 UTC, Christewart requested changes
The `cli` project needs to be updated, it doesn't support the latest rpcs

![Screenshot from 2022-06-01 09-28-51](https://user-images.githubusercontent.com/3514957/171428827-5578d01a-632c-4dac-a984-d32a6d4bfad0.png)

2022-06-01 17:26 UTC, rorp commented on app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala
> +        throw new IllegalArgumentException("password must be a string or null")
That's a password.

2022-06-01 17:31 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala
> +        throw new IllegalArgumentException("password must be a string or null")
Ah, good point.

2022-06-01 19:05 UTC, rorp commented on app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala
> +        throw new IllegalArgumentException("password must be a string or null")
No need to log a password even if it's malformed

2022-06-01 19:05 UTC, rorp commented on app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala
> +        throw new IllegalArgumentException(s"Expected json.Arr")
Same

2022-06-06 12:37 UTC, Christewart commented
This does not work with an encrypted seed. This is the error that i get when trying with local encrypted wallet

![Screenshot from 2022-06-06 07-37-04](https://user-images.githubusercontent.com/3514957/172162007-7657b19c-0520-482e-b508-d02a0342c6b2.png)

2022-06-06 13:03 UTC, Christewart commented
It doesn't seem like the `importseed` rpc is working, or i am using it incorrectly. Here is what i tried

<img width="1440" alt="Screen Shot 2022-06-06 at 8 02 03 AM" src="https://user-images.githubusercontent.com/3514957/172166024-b1ed6795-1c69-44d3-be74-ac0f199dbda4.png">

It appears the key error message here is

<img width="1440" alt="Screen Shot 2022-06-06 at 8 03 09 AM" src="https://user-images.githubusercontent.com/3514957/172166125-89024c21-8759-4daa-bea3-9e8cc7375f01.png">

>requirement failed: Number of words must be one of the following: 12, 15, 18, 21, 24, got: 1

2022-06-06 17:05 UTC, rorp commented
> It doesn't seem like the `importseed` rpc is working, or i am using it incorrectly. Here is what i tried

This PR didn't touch `importseed` that means it was broken before.

2022-06-06 17:07 UTC, rorp commented
> This does not work with an encrypted seed on 

It cannot decrypt the seed because the password is not specified

2022-06-06 18:16 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala
> +          case walletNameJs :: passJs :: Nil =>
This means the wallet name has to be defined to decrypt. I have a wallet locally that does not have a wallet name, but _does_ have a password.

2022-06-14 13:16 UTC, Christewart commented
needs rebase

2022-06-14 15:44 UTC, user411 commented on docs/applications/server.md
>      - `passphrase` - Passphrase to encrypt this seed with
encrypt -> decrypt

2022-06-14 15:58 UTC, user411 commented on docs/applications/server.md
>      - `passphrase` - Passphrase to encrypt this seed with
encrypt -> decrypt

2022-06-14 16:22 UTC, user411 commented
When I call the `exportseed` endpoint with no parameters, I am getting "org.bitcoins.keymanager.ReadMnemonicError$DecryptionError$: Could not decrypt mnemonic!"

2022-06-21 18:00 UTC, Christewart approved these changes

2022-06-22 13:14 UTC, merged