`loadwallet` endpoint
bitcoin-s/bitcoin-s pull request #4417
Opened 2022-06-23 18:52 UTC by rorp

Introduces `loadwallet`, `getwalletname` and `listwallets` endpoints

2022-06-23 18:57 UTC, user411 commented on app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
> +    case ServerCommand("getwalletname", _) =>
`walletinfo` endpoint already does this

2022-06-24 18:21 UTC, Christewart requested changes
`loadwallet`/`listwallet` need some unit tests

2022-07-08 17:48 UTC, user411 commented
I imported a new wallet and the response is {result: null, error: null}. I think we should return the new wallet name as a success signal.

2022-07-09 22:54 UTC, Christewart commented
needs rebse

2022-07-11 19:35 UTC, Christewart commented
needs rebase

2022-07-11 19:36 UTC, Christewart commented
Accidentally closed, and needs rebase

2022-07-11 19:45 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/WalletHolder.scala
> +  @volatile private var wallet: AnyDLCHDWalletApi = _
Don't use `null`

2022-07-11 19:45 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/WalletHolder.scala
> +      wallet = null
Use `Option`

2022-07-11 19:47 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/util/CallbackUtil.scala
> +        .recover { case _: WalletNotInitialized => () }
Should we log an error or warning message in these cases?

2022-07-11 19:48 UTC, Christewart commented on wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
> +        walletName = walletConfig.walletNameOpt.getOrElse(""),
nit: Maybe make a constant somewhere called 

```scala
val DEFAULT_WALLET_NAME: String = ""
```

2022-07-12 12:55 UTC, Christewart commented
`loadwallet` is not implemented in the `cli` project

2022-07-12 15:54 UTC, Christewart commented
I ran into an error this morning when trying to switch back to the default wallet on #4500 . The error message

```
Wallet `` does not exist
```

```
[info] 2022-07-12T15:49:12UTC INFO [BitcoinSServerMain] Loading wallet
[info] 2022-07-12T15:49:12UTC INFO [Server] Unhandled error in server:
[info] java.lang.RuntimeException: Wallet `` does not exist
[info]  at org.bitcoins.server.BitcoinSServerMain.$anonfun$updateWalletConfigs$1(BitcoinSServerMain.scala:662)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

![Screenshot from 2022-07-12 10-53-20](https://user-images.githubusercontent.com/3514957/178536122-5b2b8881-907d-4221-9b91-1706d4c827a8.png)

2022-07-12 19:21 UTC, rorp commented
> I ran into an error this morning when trying to switch back to the default wallet on #4500 . The error message
> 
> ```
> Wallet `` does not exist
> ```

The CLI implementation is incorrect in #4500, use this PR for CLI

2022-07-14 15:06 UTC, user411 commented
When importing a new wallet, the `height` is initially set to zero. After doing a `loadwallet` and restarting the backend with that new wallet, the `height` is set to current blockHeight.

Still need the `import` endpoints to return the wallet name for a successful import.

2022-07-14 15:15 UTC, user411 commented
When I tried a `rescan` on an imported wallet without setting `ignoreCreationTime`, I got the following:
```
[info] 2022-07-14T15:13:08UTC INFO [DLCWallet$DLCWalletImpl] Starting rescanning the wallet from None to None useCreationTime=true
[info] 2022-07-14T15:13:29UTC ERROR [DLCWallet$DLCWalletImpl] Failed to rescan wallet
[info] java.lang.RuntimeException: No block headers in database.
[info] 	at org.bitcoins.chain.models.BlockHeaderDAO.$anonfun$findClosestToTime$5(BlockHeaderDAO.scala:238)
```

2022-07-14 19:19 UTC, user411 commented
My want to have `walletinfo` take an optional parameter of wallet name so details can be pulled on all wallets without loading them.

2022-07-15 14:21 UTC, user411 commented
Calling `loadwallet` during a wallet rescan causes a hard crash on my local backend.

2022-07-18 13:10 UTC, Christewart commented
It seems when switching to a wallet that was rescanning last time we started it doesn't re-start the rescan.

![Screenshot from 2022-07-18 08-10-22](https://user-images.githubusercontent.com/3514957/179518438-a92721d2-be74-4a74-90ec-09095750eeca.png)

2022-07-18 21:47 UTC, user411 commented
First `Launch Wallet`
```
[info] 2022-07-18T21:45:28UTC INFO [BitcoinSServerMain] Starting neutrino node sync, it took=565ms
[error] org.bitcoins.wallet.WalletNotInitialized: The wallet is not initialized
[info] 2022-07-18T21:45:28UTC ERROR [BitcoinSServerMain] Failed to startup server!
[info] org.bitcoins.wallet.WalletNotInitialized: The wallet is not initialized
```
Second `Launch Wallet`
```
[info] 2022-07-18T21:46:13UTC ERROR [BitcoinSServerMain] Failed to startup server!
[info] akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: [/127.0.0.1:9999] Address already in use
[info] Caused by: java.net.BindException: [/127.0.0.1:9999] Address already in use
[error] akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: [/127.0.0.1:9999] Address already in use
[error] Caused by: java.net.BindException: [/127.0.0.1:9999] Address already in use
```
Third, after restarting everything, was same as the first. I had a non-default wallet set.

2022-07-19 16:07 UTC, Christewart commented
> First `Launch Wallet`
> 
> ```
> [info] 2022-07-18T21:45:28UTC INFO [BitcoinSServerMain] Starting neutrino node sync, it took=565ms
> [error] org.bitcoins.wallet.WalletNotInitialized: The wallet is not initialized
> [info] 2022-07-18T21:45:28UTC ERROR [BitcoinSServerMain] Failed to startup server!
> [info] org.bitcoins.wallet.WalletNotInitialized: The wallet is not initialized
> ```
> 
> Second `Launch Wallet`
> 
> ```
> [info] 2022-07-18T21:46:13UTC ERROR [BitcoinSServerMain] Failed to startup server!
> [info] akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: [/127.0.0.1:9999] Address already in use
> [info] Caused by: java.net.BindException: [/127.0.0.1:9999] Address already in use
> [error] akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: [/127.0.0.1:9999] Address already in use
> [error] Caused by: java.net.BindException: [/127.0.0.1:9999] Address already in use
> ```
> 
> Third, after restarting everything, was same as the first. I had a non-default wallet set.

Fixed in 6063a4b , forgot to replace a few variables :man_facepalming:

2022-07-19 18:42 UTC, user411 commented
Loading a wallet with a password set seemed to succeed, but next call to `walletinfo` said I have the default wallet set.
![Screen Shot 2022-07-19 at 12 40 12 PM](https://user-images.githubusercontent.com/22351459/179825157-6e27b676-f79b-4b77-b6f2-62b0dfa7c80b.png)

2022-07-20 13:42 UTC, Christewart commented
2d12a9632c4cf7f6f05e219b1edaef288000cdfb now (mostly) works with `loadwallet` honoring long running tasks like processing a block.

If a user calls `loadwallet` while our wallet is processing a block in the background, the `loadwallet` command will wait until the wallet is done processing the block, and then it will switch to the new wallet. This means that `loadwallet` can take awhile depending on what is going on in the background. It can take > 30 seconds for our wallet to process a block. This means `loadwallet` but need to wait a bit of time until the call will complete.

2022-08-05 22:34 UTC, merged