Moving duplicate dataStructures in `cli` and `app-server` into `app-commons`
bitcoin-s/bitcoin-s pull request #4541
Opened 2022-07-25 16:23 UTC by GreyMcCarthy

Comes from this PR
https://github.com/bitcoin-s/bitcoin-s/issues/4528

2022-07-25 17:25 UTC, benthecarman commented on app-commons/src/main/scala/org/bitcoins/commons/rpc/Command.scala
> +}
These should all get `defaultPort` from `AppServerCliCommand` so you dont need to override here

2022-07-28 13:02 UTC, Christewart requested changes

2022-07-28 13:02 UTC, Christewart commented on app-commons/src/main/scala/org/bitcoins/commons/rpc/Command.scala
> +trait SignDLCCliCommand extends AppServerCliCommand {}
You can remove the `{}` on these lines

2022-07-28 13:02 UTC, Christewart commented on app-commons/src/main/scala/org/bitcoins/commons/rpc/Command.scala
> +    extends CliCommand
All objects are extending too much, for instance, this is what this was `extending` before this PR

https://github.com/bitcoin-s/bitcoin-s/blob/e90e372e54cf40f846cad3f4e6fc1932d4e765d9/app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala#L469

Note, there is a difference between `case class` and `object`. 

The only objects in this file need to `extends ServerJsonModels`, that gives us access to methods like 

- `jsToPSBT`
- `jsToTx`
- `nullToOpt` 

etc

2022-07-29 19:06 UTC, Christewart requested changes

2022-07-29 19:06 UTC, Christewart commented on app/cli/src/main/scala/org/bitcoins/cli/ConsoleCli.scala
> +  /**  case class CreateContractInfo(
Can be removed?

2022-07-29 19:06 UTC, Christewart commented on app/cli/src/main/scala/org/bitcoins/cli/ConsoleCli.scala
> +  /**  trait Broadcastable {
Can be removed?

2022-07-29 19:06 UTC, Christewart commented on app/cli/src/main/scala/org/bitcoins/cli/ConsoleCli.scala
> +  /**  sealed trait SendCliCommand extends AppServerCliCommand {
Can be removed?

2022-07-29 19:06 UTC, Christewart commented on app/server/src/main/scala/org/bitcoins/server/ServerJsonModels.scala
> +/** trait Broadcastable {
Can be removed?

2022-08-02 16:55 UTC, merged