Remove redundant function checkResult
bitcoin-s/bitcoin-s pull request #565
Opened 2019-07-03 09:59 UTC by piu130

This PR removes the redundant and broken function `checkResult` from `Number`. The check is redundant, because calling apply already checks wheter the number is in the required range.

2019-07-03 15:20 UTC, torkelrogstad commented
Thanks for the contribution!

One thing which might make sense to do, is add tests that check explicitly for too small and large numbers. Something like this, in the case of `Int64`: 

```scala
  it must "throw on too small numbers" in {
    val bigint = BigInt("-9223372036854775809")
    val bigintBytes = ByteVector(bigint.toByteArray)
    an[IllegalArgumentException] must be thrownBy {
      Int64(bigint)
    }

    an[IllegalArgumentException] must be thrownBy {
      Int64.fromBytes(bigintBytes)
    }

    an[IllegalArgumentException] must be thrownBy {
      Int64.fromHex(bigintBytes.toHex)
    }
  }

  it must "throw on too large numbers" in {
    val bigint = BigInt("9223372036854775808")
    val bigintBytes = ByteVector(bigint.toByteArray)
    an[IllegalArgumentException] must be thrownBy {
      Int64(bigint)
    }

    an[IllegalArgumentException] must be thrownBy {
      Int64.fromBytes(bigintBytes)
    }

    an[IllegalArgumentException] must be thrownBy {
      Int64.fromHex(bigintBytes.toHex)
    }
  }
```

Another thing which might also be of interest, is a couple of commits I worked on a while ago without making a PR out of: https://github.com/torkelrogstad/bitcoin-s/commit/ca1f6ed8221211d937408d2f5f54d114a834832b and https://github.com/torkelrogstad/bitcoin-s/commit/e15a845ffab16b611bf966712af0b574e6bd719d. The general idea is to remove as many invariants as possible in `NumberType`, and have _one_ place that's able to check all invariants generically. If you think that approach is any good, that might make sense to incorporate here?

2019-07-07 08:14 UTC, piu130 commented
@torkelrogstad I currently don't have the time to write tests for all those numbers. Sorry.

I think we should generalize the behaviour of 'call require in apply' by abstracting the method `isValid` in `UInt8` for all numbers. Then we can test whether isValid is called in the constructor.

2019-07-08 08:44 UTC, torkelrogstad commented
The `isValid` approach sounds good! Do you mind expanding your PR to incorporate that?

2019-07-10 07:24 UTC, piu130 commented
@torkelrogstad I implemented `isValid` called `isInBound` and moved `min` and `max` to the new trait `Bounded`. `zero` and `one` are more identity elements while `min` and `max` are bounds for some but not all numbers.
This is also to prepare for the [Numeric](https://www.scala-lang.org/api/current/scala/math/Numeric.html) trait in Scala which contains `zero` and `one` but not `min` and `max`.

What do you think about it?

Should we remove the methods marked with `@deprecated`? Or do you prefer it this way?

2019-07-10 10:03 UTC, torkelrogstad requested changes
Great work! I think just deleting the deprecated methods is fine, seeing as we haven't reached a 1.x release yet. I'm fine with merging in this PR after that.

2019-07-10 10:03 UTC, torkelrogstad commented on core/src/main/scala/org/bitcoins/core/number/NumberType.scala
> +trait Bounded[T] {
Do you mind adding a short Scaladoc here? Something like "Represents number types that are bounded by minimum and maximum values"

2019-07-10 11:56 UTC, piu130 commented
@torkelrogstad done.

I think you should add scalafmt to travis (if possible) so the build would fail, if the code is not formatted correctly.

2019-07-10 15:25 UTC, torkelrogstad commented
Looks like there's some weirdness going on in CI . I'll restart the build and see what happens.

2019-07-10 15:47 UTC, torkelrogstad commented
Looks like all of CI is screwed up now for some reason. Think I've seen the error message before, but can't remember how I solved it. I'll restart the build a bit later and see if anything changes, otherwise we'll just merge this.

2019-07-11 10:58 UTC, torkelrogstad approved these changes

2019-07-11 11:01 UTC, torkelrogstad commented
CI is having issues, so I pulled down and ran tests locally. LGTM!

2019-07-11 11:01 UTC, merged