Add notion of address types in wallet
bitcoin-s/bitcoin-s pull request #590
Opened 2019-07-10 15:15 UTC by torkelrogstad

In this commit we
1) Add the notion of address types in the wallet, and remove
    the emphasis on account types. Users now just request
    a segwit/nested-segwit/legacy address, and we take care
    of querying for the correct account
2) Fix a bug where a wallet could only get addresses for
    its default address type. This was a pretty minor bug,
    where a few values that should have been dynamic was
    hard coded.

2019-07-13 14:18 UTC, Christewart requested changes

2019-07-13 14:18 UTC, Christewart commented on wallet/src/main/scala/org/bitcoins/wallet/AddressType.scala
> +object AddressType {
Perhaps move into core?

2019-07-13 14:18 UTC, Christewart commented on wallet/src/main/scala/org/bitcoins/wallet/internal/AddressHandling.scala
> +  def getNewAddress(addressType: AddressType): Future[BitcoinAddress] = {
nit: `override`

2019-07-15 17:49 UTC, nkohen commented on wallet-test/src/test/scala/org/bitcoins/wallet/LegacyWalletTest.scala
> +      // assert(nested.isInstanceOf[P2SHAddress])
Does this have an issue?

2019-07-15 17:49 UTC, nkohen commented on wallet/src/main/scala/org/bitcoins/wallet/api/WalletApi.scala
> +  // TODO: Last sentence is not true, implement that
issue?

2019-07-16 12:01 UTC, merged